create table public.projects (
    id bigint generated by default as identity,
    --
    name text not null,
    image text not null default 'data:null',
    content jsonb null,
    owner_id uuid not null,
    --
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint projects_pkey primary key (id),
    constraint public_projects_owner_id_fkey foreign key (owner_id) references auth.users (id) on delete cascade
) tablespace pg_default;

create table public.triggers (
    node_id text not null,
    plugin_id text not null,
    project_id bigint not null,
    --
    config jsonb,
    --
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint public_triggers_pkey primary key (node_id, plugin_id, project_id),
    constraint public_triggers_project_id_fkey foreign key (project_id) references public.projects (id) on delete cascade
) tablespace pg_default;